resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - worker-config-configmap.yaml
  - api-service.yaml
  - worker-service.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - poddisruptionbudgets.yaml
  - networkpolicies.yaml
  - secretproviderclass-vault.yaml
