apiVersion: v1
kind: Service
metadata:
  name: avantii-web
  namespace: dpdp-compliance
spec:
  selector:
    app.kubernetes.io/name: avantii-web
  ports:
    - name: http
      port: 3000
      targetPort: http
